# This file contains all available configuration options
# with their default values.

# options for analysis running
run:
  # timeout for analysis, e.g. 30s, 5m, default is 1m
  deadline: 5m

  # exit code when at least one issue was found, default is 1
  issues-exit-code: 1

  # include test files or not, default is true
  tests: false

# # all available settings of specific linters
linters-settings:
  govet:
    # report about shadowed variables
    check-shadowing: true
  golint:
    # minimal confidence for issues, default is 0.8
    min-confidence: 0.5
  gocyclo:
    # minimal code complexity to report, 30 by default (but we recommend 10-20)
    min-complexity: 50
  maligned:
    # print struct with more effective memory layout or not, false by default
    suggest-new: true
  depguard:
    list-type: blacklist
    include-go-root: false
    packages:
      - github.com/davecgh/go-spew/spew
  misspell:
    ignore-words:
      - newrelic
  lll:
    # max line length, lines longer will be reported. Default is 120.
    # '\t' is counted as 1 character by default, and can be changed with the tab-width option
    line-length: 300 # setting high as tests have long payloads currently

linters:
  enable-all: true
  disable:
    - dupl
    - gochecknoglobals
    - interfacer
    - goimports
    - maligned
    - scopelint
    - wsl
    - funlen
    - whitespace
    - godox
    - gocognit
    - gomnd
    - unparam # switch back on later
    - gocritic # switch back on later

issues:
  exclude-rules:
    - text: "G402:"
      linters:
        - gosec
