# Pull specific ubuntu 22.04 image
FROM ubuntu@sha256:1e622c5f073b4f6bfad6632f2616c7f59ef256e96fe78bf6a595d1dc4376ac02


# Path of nri-flex
ARG flex_bin

# Path of the binary tests
ARG flex_tests_bin

# Add the nri-flex binary
COPY $flex_bin /bin/nri-flex
COPY $flex_tests_bin /bin/flex_tests_bin


CMD ["/bin/flex_tests_bin", "-test.v"]
