# Pull specific ubuntu 22.04 image
FROM ubuntu@sha256:72297848456d5d37d1262630108ab308d3e9ec7ed1c3286a32fe09856619a782


# Path of nri-flex
ARG flex_bin

# Path of the binary tests
ARG flex_tests_bin

# Add the nri-flex binary
COPY $flex_bin /bin/nri-flex
COPY $flex_tests_bin /bin/flex_tests_bin


CMD ["/bin/flex_tests_bin", "-test.v"]
