# Pull specific ubuntu 22.04 image
FROM ubuntu@sha256:2e863c44b718727c860746568e1d54afd13b2fa71b160f5cd9058fc436217b30


# Path of nri-flex
ARG flex_bin

# Path of the binary tests
ARG flex_tests_bin

# Add the nri-flex binary
COPY $flex_bin /bin/nri-flex
COPY $flex_tests_bin /bin/flex_tests_bin


CMD ["/bin/flex_tests_bin", "-test.v"]
