#!/bin/sh

cd /home/$1/sqllib

. ./db2profile

db2 connect to $2

db2 -x "SELECT SNAPSHOT_TIMESTAMP, BP_NAME, TOTAL_PHYSICAL_READS, AVERAGE_READ_TIME_MS, TOTAL_ASYNC_READS, AVERAGE_ASYNC_READ_TIME_MS, TOTAL_SYNC_READS, AVERAGE_SYNC_READ_TIME_MS, PERCENT_SYNC_READS, ASYNC_NOT_READ_PERCENT, DBPARTITIONNUM, MEMBER FROM SYSIBMADM.BP_READ_IO"

exit 0