#!/bin/sh

cd /home/$1/sqllib

. ./db2profile

db2 connect to $2

db2 -x "SELECT SNAPSHOT_TIMESTAMP, DB_NAME, AGENT_ID, APPL_NAME, AUTHID, TBSP_NAME, TABSCHEMA, TABNAME, SUBSECTION_NUMBER, LOCK_OBJECT_TYPE, LOCK_WAIT_START_TIME, LOCK_NAME, LOCK_MODE, LOCK_MODE_REQUESTED, AGENT_ID_HOLDING_LK, APPL_ID_HOLDING_LK, LOCK_ESCALATION, DBPARTITIONNUM, MEMBER FROM SYSIBMADM.LOCKWAITS"

exit 0