#!/bin/sh

cd /home/$1/sqllib

. ./db2profile

db2 connect to $2

db2 -x "SELECT SNAPSHOT_TIMESTAMP, NUM_EXECUTIONS, AVERAGE_EXECUTION_TIME_S, STMT_SORTS, SORTS_PER_EXECUTION, STMT_TEXT, DBPARTITIONNUM, MEMBER FROM SYSIBMADM.TOP_DYNAMIC_SQL"

exit 0