#!/bin/sh

cd /home/$1/sqllib

. ./db2profile

db2 connect to $2

db2 -x "SELECT APPLICATION_HANDLE, TOTAL_CPU_TIME, ROWS_READ, ROWS_RETURNED, TOTAL_WAIT_TIME, TOTAL_SORTS FROM TABLE(MON_GET_UNIT_OF_WORK(NULL,-1)) AS t ORDER BY TOTAL_CPU_TIME DESC"

exit 0