#!/bin/sh

cd /home/$1/sqllib

. ./db2profile

db2 connect to $2

db2 -x "SELECT SUBSTR(STMT_TEXT, 1, 50) AS STMT_TEXT, AGENT_ID, ELAPSED_TIME_MIN, APPL_STATUS, DBPARTITIONNUM  FROM SYSIBMADM.LONG_RUNNING_SQL ORDER BY DBPARTITIONNUM"

exit 0