#!/bin/sh

cd /home/$1/sqllib

. ./db2profile

db2 connect to $2

db2 -x "SELECT SNAPSHOT_TIMESTAMP, DB_NAME, BP_NAME, TOTAL_LOGICAL_READS, TOTAL_PHYSICAL_READS, TOTAL_HIT_RATIO_PERCENT, DATA_LOGICAL_READS, DATA_PHYSICAL_READS, DATA_HIT_RATIO_PERCENT, INDEX_LOGICAL_READS, INDEX_PHYSICAL_READS, INDEX_HIT_RATIO_PERCENT, XDA_LOGICAL_READS, XDA_PHYSICAL_READS, XDA_HIT_RATIO_PERCENT, DBPARTITIONNUM, MEMBER FROM SYSIBMADM.BP_HITRATIO"

exit 0