#!/bin/sh

cd /home/$1/sqllib

. ./db2profile

db2 connect to $2

db2 -x "SELECT SNAPSHOT_TIMESTAMP, NUM_EXECUTIONS, AVERAGE_EXECUTION_TIME_S, AVERAGE_EXECUTION_TIME_MS, PREP_TIME_MS, PREP_TIME_PERCENT, STMT_TEXT, DBPARTITIONNUM, MEMBER FROM SYSIBMADM.QUERY_PREP_COST"

exit 0