#!/bin/sh

cd /home/$1/sqllib

. ./db2profile

db2 connect to $2

db2 -x "SELECT SNAPSHOT_TIMESTAMP, TBSP_ID, TBSP_NAME, TBSP_TYPE, TBSP_CONTENT_TYPE, TBSP_CREATE_TIME, TBSP_STATE, TBSP_TOTAL_SIZE_KB, TBSP_USABLE_SIZE_KB, TBSP_USED_SIZE_KB, TBSP_FREE_SIZE_KB, TBSP_UTILIZATION_PERCENT, TBSP_TOTAL_PAGES, TBSP_USABLE_PAGES, TBSP_USED_PAGES, TBSP_FREE_PAGES, TBSP_PAGE_TOP, TBSP_PAGE_SIZE, TBSP_EXTENT_SIZE, TBSP_PREFETCH_SIZE, TBSP_MAX_SIZE, TBSP_INCREASE_SIZE, TBSP_INCREASE_SIZE_PERCENT, TBSP_LAST_RESIZE_TIME, TBSP_LAST_RESIZE_FAILED, TBSP_USING_AUTO_STORAGE, TBSP_AUTO_RESIZE_ENABLED, DBPGNAME, TBSP_NUM_CONTAINERS, REMARKS,DBPARTITIONNUM FROM SYSIBMADM.TBSP_UTILIZATION"

exit 0