configurationDefinitions:
  - platform: HOST
    type: AgentConfig
    version: 1.0.0
    format: yml
    operatingSystem: LINUX
    bindings:
      - type: CONFIGURES
        targetType: AGENT
        target: NRIFlex
        versions:
          - ">1.18.0"
  - platform: HOST
    type: AgentConfig
    version: 1.0.0
    format: yml
    operatingSystem: WINDOWS
    bindings:
      - type: CONFIGURES
        targetType: AGENT
        target: NRIFlex
        versions:
          - ">1.18.0"
