configurationDefinitions:
  - platform: HOST
    description: flex integration configuration
    type: agent-config
    version: 1.0.0
    format: yml
    operatingSystem: LINUX
  - platform: HOST
    description: flex integration configuration
    type: agent-config
    version: 1.0.0
    format: yml
    operatingSystem: WINDOWS
