FROM golang:1.13 as builder
ARG CGO_ENABLED=0
WORKDIR /go/src/github.com/newrelic/nri-flex
COPY . .
RUN go build -o bin/https-server integration-test/https-server/https-server.go

FROM alpine:3.9
ADD integration-test/https-server/cabundle /cabundle
COPY --from=builder /go/src/github.com/newrelic/nri-flex/bin/https-server /
CMD ["/https-server"]
