apiVersion: v1
kind: Service
metadata:
  name: https-server
spec:
  selector:
    app: https-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      name: http
    - port: 443
      targetPort: 8043
      name: https
---
apiVersion: v1
kind: Pod
metadata:
  name: https-server
  labels:
    app: https-server
spec:
  restartPolicy: Always
  containers:
  - name: http-server
    image: newrelic/https-server:integration-test
    command: ["/http-server"]
    ports:
      - containerPort: 8080
    imagePullPolicy: Never
  - name: https-server
    image: newrelic/https-server:integration-test
    command: ["/https-server"]
    ports:
      - containerPort: 8043
    imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-db
  labels:
    app: postgres-db
spec:
  #type: NodePort
  ports:
   - port: 5432
  selector:
   app: database-server
---
apiVersion: v1
kind: Pod
metadata:
  name: database-server
  labels:
    app: database-server
spec:
  restartPolicy: Always
  containers:
  - name: postgres
    image: postgres:11.7-alpine
    imagePullPolicy: IfNotPresent
    ports:
      - containerPort: 5432
    env:
      - name: POSTGRES_PASSWORD
        value: flex
