name: httpsTest
apis:
  - name: httpsTest
    url: https://localhost:$$TEST_HTTPS_SERVER_PORT/json
    event_type: WindowsHttpSample
    start_key: 
      - metrics
    tls_config:
      enable: true
      insecure_skip_verify: true
