name: nginxFlex
apis:
  - name: nginxStub
    url: http://https-server/nginx_status # get stub status output
    ignore_output: true
  - name: nginx
    entity: https-server
    event_type: NginxSample
    commands:
      - cache: http://https-server/nginx_status # use commands to parse the response
        split_output: Active
        regex_matches:
          - expression: Active connections:\s(\S+)
            keys: [net.connectionsActive]
          - expression: \s?(\d+)\s(\d+)\s(\d+)
            keys: [net.connectionsAcceptedPerSecond, net.handledPerSecond, net.requestsPerSecond]
          - expression: Reading:\s(\d+)\s\S+\s(\d+)\s\S+\s(\d+)
            keys: [net.connectionsReading, net.connectionsWriting, net.connectionsWaiting]
    math:
      net.connectionsDroppedPerSecond: ${net.connectionsAcceptedPerSecond} - ${net.handledPerSecond}