# Used to query Directory Size via Disk Usage
name: linuxDirectorySize
apis:
  - name: linuxDirectorySize
    commands:
      - run: du -c $$DIR
        split: horizontal
        set_header: [dirSizeBytes,dirName]
        regex_match: true
        split_by: (\d+)\s+(.*)