# Used to get list of windows services
name: windowsServiceList
apis:
  - name: windowsServiceList
    commands:
      # shell in windows doesn't work properly. just run powershell direclty.
      # on a real powershell shell just add the command like
      - run: powershell  service
        event_type: WindowsCommand
        split: horizontal
        set_header: [status,name,displayname]
        row_start: 1
        regex_match: true
        split_by: (\w+)\s+(\w+)\s+(\w+)