#!/usr/bin/env bash

set -u
set -o pipefail

JAR="/usr/lib/nrjmx/nrjmx.jar"
if [[ ! -s "${JAR}" ]];then
    # Gets the directory where the script is located. Works on mac or linux
    SCRIPTDIR="$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd -P)"
    JAR="${SCRIPTDIR}/nrjmx.jar"
fi

if [[ ! -s "${JAR}" ]];then
    echo "ERROR - jar ${JAR} does not exist" > /dev/stderr
    exit 1
fi

JAVA="${JAVA_HOME:-}/bin/java"
if [[ ! -s "${JAVA}" ]];then
    JAVA=$(which java 2> /dev/null)
fi

if [[ ! -s "${JAVA}" ]];then
    echo "ERROR - unable to find java binary on PATH or in JAVA_HOME/bin" > /dev/stderr
    exit 1
fi

"${JAVA}" -jar "${JAR}" $@

