integration_name: com.kav.nri-flex

instances:
  - name: nri-flex
    command: metrics
    arguments:
      # container_discovery: true ## default false
      # config_file: "../myConfigFile.yml" ## default ""
      # config_dir: "anotherConfigDir/" ## default "flexConfigs"
      # event_limit: 500 ## default 500
    # labels:
      # owner: cloud