name: Run unit tests

on:
  pull_request:
    paths:
      - "**/*.go"
  push:
    paths:
      - "**/*.go"

jobs:
  test:
    runs-on: ubuntu-lastest
    steps:
      - name: Install go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13.x
      - name: unit-test
        uses: actions/checkout@v2
        run: |
          make clean test 
