name: Run unit tests

# runs-on: ${{matrix.os}}
# strategy:
#   matrix:
#     os: [ubuntu-16.04, windows]

on:
  pull_request:
    # paths:
    #   - "**/*.go"
  push:
    # paths:
    #   - "**/*.go"
    #   - "**/*.yaml"

jobs:
  test:
    stategy:
      matrix:
        go: ['1.13.4']
        os: [ubuntu-16.04, windows]
    name: Run unit tests with go ${{matrix.os}} - ${{matrix.go}}
    runs-on: ubuntu-lastest
    steps:
      - name: Install go
        uses: actions/setup-go@v1
        with:
          go-version: ${{matrix.go}}
        id: gosetup
      - name: Build container image
        run: docker build . --file integration-test/Dockerfile --tag newrelic/nri-flex:integration-test
      - name: checkout
        uses: actions/checkout@v2
      - name: unit-test
        run: |
          docker run --it --rm newrelic/nri-flex:integration-test go test ./...
        id: test 
