name: Run unit tests

# runs-on: ${{matrix.os}}
# strategy:
#   matrix:
#     os: [ubuntu-16.04, windows]

on: [push, pull_request]
  # pull_request:
    # paths:
    #   - "**/*.go"
  # push:
    # paths:
    #   - "**/*.go"
    #   - "**/*.yaml"

jobs:
  test:
    strategy:
      matrix:
        go: ['1.13.4']
        os: [ubuntu-latest, windows-latest]
    name: Run unit tests with go ${{matrix.os}} - ${{matrix.go}}
    runs-on: ${{matrix.os}}
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: install go
        uses: actions/setup-go@v2
        with:
          go-version: ${{matrix.go}}
      - name: build container image
        run: docker build . --file Dockerfile.tests --tag newrelic/nri-flex:integration-test
      - name: run tests in container
        run: |
          docker run --attach --rm newrelic/nri-flex:integration-test go test ./...
